# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer', models.CharField(max_length=250)),
                ('pic_title', models.CharField(max_length=500)),
                ('pic_type', models.CharField(max_length=100)),
                ('pic_logo', models.CharField(max_length=1000)),
            ],
        ),
    ]
